# Generated by Django 4.1.7 on 2023-03-01 01:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMuscular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreinoAluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_expiracao', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='dt_vencimentoPlano',
            field=models.DateField(null=True),
        ),
    ]
