# Generated by Django 4.2 on 2023-05-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0003_exercicio_id_grupomuscular_treinoaluno_id_excecicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
