# Generated by Django 4.2 on 2023-05-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0004_exercicio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='id_Aluno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treino',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treinoaluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
