# Generated by Django 4.2 on 2023-05-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0005_alter_aluno_id_aluno_alter_exercicio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Senha',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='fl_ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
