# Generated by Django 4.2 on 2023-06-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0006_aluno_senha_aluno_fl_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='id',
            new_name='id_Excecicio',
        ),
        migrations.RenameField(
            model_name='grupomuscular',
            old_name='id',
            new_name='id_GrupoMuscular',
        ),
        migrations.RenameField(
            model_name='treino',
            old_name='id',
            new_name='id_Treino',
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='id_GrupoMuscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cadastros.grupomuscular'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='treinoaluno',
            name='id_Excecicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cadastros.exercicio'),
        ),
        migrations.AlterField(
            model_name='treinoaluno',
            name='id_GrupoMuscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cadastros.grupomuscular'),
        ),
        migrations.AlterField(
            model_name='treinoaluno',
            name='id_Treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cadastros.treino'),
        ),
        migrations.AlterField(
            model_name='treinoaluno',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.aluno'),
        ),
    ]
